# fly.toml app configuration file generated for tradeflow on 2025-08-19T01:52:22-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tradeflow'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[processes]
  app = './start.sh'

[[mounts]]
  source = 'tradeflow_data'
  destination = '/data'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
