# Arquivo: alembic/versions/09d80b6e64de_add_coin_whitelist_to_users.py

"""add_coin_whitelist_to_users

Revision ID: 09d80b6e64de
Revises: 
Create Date: 2025-08-22 12:03:06.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d80b6e64de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('coin_whitelist', sa.String(), server_default='todas', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'coin_whitelist')
    # ### end Alembic commands ###