"""adiciona disjuntor de performance

Revision ID: 5b09bd7eb0c6
Revises: 75d8eb493a4f
Create Date: 2025-08-25 17:47:40.276438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5b09bd7eb0c6'
down_revision: Union[str, Sequence[str], None] = '75d8eb493a4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unrealized_pnl_pct', sa.Float(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        # CORREÇÃO: Adicionado server_default para as colunas NOT NULL
        batch_op.add_column(sa.Column('circuit_breaker_threshold', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('circuit_breaker_pause_minutes', sa.Integer(), nullable=False, server_default='60'))
        batch_op.add_column(sa.Column('long_trades_paused_until', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('short_trades_paused_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('short_trades_paused_until')
        batch_op.drop_column('long_trades_paused_until')
        batch_op.drop_column('circuit_breaker_pause_minutes')
        batch_op.drop_column('circuit_breaker_threshold')

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_column('unrealized_pnl_pct')
    # ### end Alembic commands ###