"""adiciona_filtros_de_analise_tecnica

Revision ID: 657fc8fb3f24
Revises: c19acb6f35e0
Create Date: 2025-08-26 18:19:40.264746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '657fc8fb3f24'
down_revision: Union[str, Sequence[str], None] = 'c19acb6f35e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_ma_filter_enabled', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('ma_period', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('ma_timeframe', sa.String(length=10), nullable=False))
    op.add_column('users', sa.Column('is_rsi_filter_enabled', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('rsi_timeframe', sa.String(length=10), nullable=False))
    op.add_column('users', sa.Column('rsi_oversold_threshold', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('rsi_overbought_threshold', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rsi_overbought_threshold')
    op.drop_column('users', 'rsi_oversold_threshold')
    op.drop_column('users', 'rsi_timeframe')
    op.drop_column('users', 'is_rsi_filter_enabled')
    op.drop_column('users', 'ma_timeframe')
    op.drop_column('users', 'ma_period')
    op.drop_column('users', 'is_ma_filter_enabled')
    # ### end Alembic commands ###
