"""Adiciona estrategia de stop e high water mark

Revision ID: 6a9989511a3b
Revises: 72957ba18a40
Create Date: 2025-08-24 01:25:53.154380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a9989511a3b'
down_revision: Union[str, Sequence[str], None] = '72957ba18a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('trail_high_water_mark', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('stop_strategy', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stop_strategy')
    op.drop_column('trades', 'trail_high_water_mark')
    # ### end Alembic commands ###
