"""Adiciona estrategia de stop e high water mark

Revision ID: 6a9989511a3b
Revises: 72957ba18a40 # Verifique se este é o ID da sua migração anterior (a do is_breakeven)
Create Date: 2025-08-24 04:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a9989511a3b'
down_revision: Union[str, Sequence[str], None] = '72957ba18a40' # Verifique o ID da revisão anterior aqui
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trail_high_water_mark', sa.Float(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        # CORREÇÃO: Adicionado server_default para compatibilidade com SQLite
        batch_op.add_column(sa.Column('stop_strategy', sa.String(length=20), nullable=False, server_default='BREAK_EVEN'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('stop_strategy')

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_column('trail_high_water_mark')

    # ### end Alembic commands ###