"""Adiciona is_breakeven na tabela de trades

Revision ID: 72957ba18a40
Revises: 77721795cc18
Create Date: 2025-08-24 01:07:45.256965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72957ba18a40'
down_revision: Union[str, Sequence[str], None] = '77721795cc18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('is_breakeven', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'is_breakeven')
    # ### end Alembic commands ###
