"""adiciona notification message id a sinais pendentes

Revision ID: 8556fc30af64
Revises: 72414141c92a
Create Date: 2025-08-25 11:12:01.229846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8556fc30af64'
down_revision: Union[str, Sequence[str], None] = '72414141c92a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_signals', sa.Column('notification_message_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_signals', 'notification_message_id')
    # ### end Alembic commands ###
