"""Adiciona contagem total de alvos aos trades

Revision ID: 88671eb031a1
Revises: 9d5e9e4281e6
Create Date: 2025-08-25 00:07:46.344647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88671eb031a1'
down_revision: Union[str, Sequence[str], None] = '9d5e9e4281e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('total_initial_targets', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'total_initial_targets')
    # ### end Alembic commands ###
