"""add trades.missing_cycles and last_seen_at

Revision ID: ea992c8d7b70
Revises: b2a5a70c97b3
Create Date: 2025-08-29 12:39:12.562656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea992c8d7b70'
down_revision: Union[str, Sequence[str], None] = 'b2a5a70c97b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
