"""add tp_distribution to users table

Revision ID: f3d6de56aebe
Revises: 66975bf22f34
Create Date: 2025-09-02 03:23:18.824917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d6de56aebe'
down_revision: Union[str, Sequence[str], None] = '66975bf22f34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tp_distribution', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tp_distribution')
    # ### end Alembic commands ###
