# Nome do Workflow que aparecerá na aba "Actions" do GitHub
name: Deploy Tradeflow to VPS

# Gatilho: Este workflow roda a cada push na branch 'main'
on:
  push:
    branches:
      - main

# Tarefas que o workflow irá executar
jobs:
  deploy:
    # O sistema operacional que o robô do GitHub usará
    runs-on: ubuntu-latest

    # Passos a serem executados
    steps:
      - name: Deploy to VPS via SSH
        # Usa uma Action pronta da comunidade para SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          # Usa os segredos que você configurou
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}

          # Script com os comandos a serem executados na VPS
          script: |
            set -euo pipefail
            # Navega para a pasta da aplicação
            cd /srv/apps/tradeflow

            echo "==> Atualizando o código-fonte..."
            git fetch origin
            git reset --hard origin/main

            # --- SEÇÃO MODIFICADA ---
            # O comando a seguir faz tudo de uma vez:
            #   - --build: Reconstrói a imagem se o Dockerfile ou o código mudaram.
            #   - --force-recreate: Para e recria os contêineres, forçando a atualização.
            #   - --remove-orphans: Remove contêineres de serviços antigos.
            #   - -d: Roda em background.
            echo "==> Reconstruindo e reiniciando o serviço..."
            sudo docker-compose up -d --build --force-recreate --remove-orphans

            echo "==> Limpando imagens Docker antigas..."
            sudo docker image prune -af

            echo "==> Verificando serviços ativos..."
            sudo docker-compose ps
